### PR TITLE
Fixed the error checking as it was not working with Episys release 20…

### PR DESCRIPTION
**Pull request by Vysion34**
…17.00 Final.

Also resolved all Java warnings within the file that was modified for the error checking fix.

### CODE REVIEW

**Comment by thechillman422** [comment]
Hi Dean,  Just to clarify, this is to fix the issues that CU's are having with the 2017.00? Since I do not have 2017.00 yet, I cannot test it.  Have you asked any of the affected users to test it out? and how long have you tested your code?  Thanks, I appreciate it.

**Comment by Vysion34** [comment]
Hi Jake,

Yes this was to fix error checking when using 2017.00 release of episys. I
tested it multiple times with both 2016 and 2017 episys to make sure it
didn't break 2016. I also reverted it back for another test to make sure it
fixed the issue. Another user named Forrest said he was going to test it
out as well but I don't know if he has tested it yet. I can get someone
else to test it before you accept the changes.

Best regards,

Dean

**Comment by thechillman422** [comment]
Hi Dean,

Good to know.  I was helping Forrest get started on trying to fix the errors.  But because neither of us had 2017 at the time, it was hard to troubleshoot.  As of last week, Forrest had access to 2017.  I can follow up with him Monday to see how his testing goes.  If it tests successful, I can merge your patch.  Thanks for working on this ! ! !

Bruce

**Comment by faithfulman18** [comment]
Any idea when a new release will be created with these fixes?

**Comment by Buckmarble** [comment]
Soon probably. Testing is going well on my end for 2016. My 2017 syms have been backup and deleted to us having to add more storage to our symitar box so I won't be able to test 2017 until thrusday or friday.

**Comment by Vysion34** [comment]
Bruce,

My bad for getting people confused when I replied to your email on Saturday
night. I was confused on who the email came from and it didn't help that I
was several beers deep at a house party watching the Mayweather vs Mcgregor
fight. I just realized now that Github masks user's emails with the
repository name, which added to the confusion.

Forrest and I were working this morning on fixing the Ant build script to
compile the project correctly.

I plan on spending more time tomorrow trying to fix the issue with running
specfiles on a 2017.00 release as well as displaying the reports after they
run. I am thinking the first issue may just fix the 2nd one.

Dean

**Comment by thechillman422** [comment]
I believe Eric, aka Rev2106 may have a fix for the installing issue.  See https://github.com/jakepoz/RepDev/issues/10.  I will review his changes.

**Comment by Vysion34** [comment]
I can incorporate his suggestions this afternoon and test it.

**Comment by thechillman422** [comment]
P.S.  no worries on the name confusion.  Jake is the creator of RepDev and this is his repository +1 +1 +1, oh heck, who am I kidding +1,000,000 (Thanks Jake) :D

**Comment by jakepoz** [comment]
Thanks! :) 

Bruce (aka thechillman422) is running the repository now so it's in good hands :)

**Comment by Vysion34** [comment]
I've included Eric's suggested fixes and have tested in both 2016 and 2017
Episys releases. I have error checking, report running, and installing
working in both 2016 and 2017. No exceptions so far during my testing. I
also included Eric's suggestion for the periodic issue where reports are
not displaying after running a specfile, although I cannot reliably test it
as I don't know how to get the environment into a state that produces the
issue that Eric described. However the suggested fix does not cause any
further errors or exceptions. I will push that one in a separate commit so
it can be further tested by others before confirmed a legit fix.

Dean

**Comment by thechillman422** [comment]
Dean, I've Commited your code.  Please double check everything to make sure it is ok.  Then I'll bump the Rev and build the x86 and x64 Downloads for everyone to use.   Let me know when you are ready.  Thanks.

**Comment by Vysion34** [comment]
Bruce,

I'll get it tested shortly here. I will fetch your repository and test it
on both 2016 and 2017 Episys.

I am having an issue with the RepDev.exe launcher as of right now. I went
to go use the existing version of repdev from before and it now wont launch
and says: "This application requires a Java Runtime Environment 1.5.0"
I've never had the JRE 1.5 before and it always worked, but now after all
this development it isn't working. I am thinking it is because I changed my
JAVA_HOME environment variable to the JDK. Have you seen this before?

I am using RepDev from inside the Eclipse IDE as a work around for the time
being.

Thanks,

Dean

**Comment by Buckmarble** [comment]
Try what i have on my fork. I have no issues with using the new and old versions of repdev.

**Comment by thechillman422** [comment]
Dean, I've already merged your request and committed the code, and bumped the version to 1.6.12.  I was able to build and launch RepDev on my side.  I am in the process of pushing out the binarys.  I'll let you know when it's done.

**Comment by Buckmarble** [comment]
I had problems with Dean's patches with 2017. If someone could check them to make sure it is or isn't just me.

**Comment by thechillman422** [comment]
I've updated the binarys.  Can you guys download the 32 and the 64 bit versions and test them out.  Thanks.

**Comment by Vysion34** [comment]
I finally have time to test. I will download the master repository first
and test in the IDE. Then I will download the binaries and test those.


A side note: I had updated the repdev project to have a minimum required
Java version of 1.7. Honestly for security concerns it should be a minimum
of 1.8, but I know some users might still have 1.7 installed for legacy
purposes. Does the group agree with raising the minimum JRE version in the
launcher from 1.5 to at least 1.7 to coincide with the repdev project? I
just wanted to bring that up as a discussion point.

Thanks,

Dean

**Comment by Buckmarble** [comment]
I would agree. You actually can't even download java7(1.7) any more I don't think. I tried to download 1.7 when I was trying to get it built and couldn't find a good link for it.

**Comment by Vysion34** [comment]
I tested the code on the jakepoz/repdev master branch. It is working fine
when I run it from the IDE. Fixes the issues with 2017 Episys. However I am
still having trouble with the launcher. I am looking into the issue but I
believe it is just a problem on my system. I think it started after I
installed the 1.8 JDK. I am trying to reinstall everything to see if I can
fix my issue. Otherwise the code works great on both 2016 and 2017 Episys.
Hopefully someone else has been able to test on their system to confirm my
results.

Forrest, Java 1.7 can be downloaded still, but it is hard to find. You have
to Google "Java 7" to find the download page. Oracle doesn't make it easy
to find because they want normal users to install Java 8 for security
reasons. Java 7 had some glaring security vulnerabilities.

Dean

**Pull request merged**
