### PR TITLE
Line Numbering and Logon Hanging

### PR DESCRIPTION
**Pull request by lagarzab**
Added Line Numbers to left margin for all files
- Allows for easier collaboration

Added more logic to handle 'logon hang' when unexpected response from
Symitar is received.  (This should address Issue #5 as unexpected responses should terminate the connection attempt to the SYM.)
- Checks for possibility that console isn't setup as 'Symitar for
Windows PC'.
- Checks for possibility that PC's IP isn't configured for use with
Symitar.
- If unexpected prompt is received, session will be disconnected and
user will be prompted, instead of hanging.

### CODE REVIEW

**Comment by thechillman422** [comment]
Hi Bryan, This looks great, thanks for submitting this.  I will test it for a couple of days before I merge the code.  Question, do you think you have time to add it to "Tools", "Options", Editor Options"? Some people may not want to see the line number all the time.  If not, no worries.  Let me know.  Thanks.

Bruce

**Comment by lagarzab** [comment]
Great suggestion, Bruce.  
Line Numbers Feature can now be enabled/disabled via Tools > Options > Editor Options > Display line numbers.

Bryan

**Comment by thechillman422** [comment]
Hi Bryan,  Thanks for the quick turn-around.  But for some reason, The Style no longer works for me.  No matter what style I chose, it is defaulted to the Default Style.  Are you able to select and use the various Styles?

**Comment by lagarzab** [comment]
Hi Bruce, 
Sorry, I started down one road and changed it up along the way.  XML styling should work again.

I am capturing the font color of comments and applying that to the line numbers.  This made more sense to me, than allowing users to define their own color (my original thought).  This will allow the numbers to, more or less, blend in with other pieces of "ignored" code.

Bryan

**Comment by thechillman422** [comment]
Hi Bryan,  The Styles works now.  I will continue to test it this week and then merge the change.  Thanks again ! ! !

P.S. I would have preferred the line number in grey as you had originally, mainly because my comments are Green :D But it's ok.  Maybe we can add it as it's own Style within the xml file in the near future i.e. <linenum fgColor="#808080"/>

**Comment by thechillman422** [comment]
looks like part of my comment was stripped out.  Let's try again;
keywords fgColor="#7F7F7F"

**Comment by thechillman422** [comment]
Bryan, I finally had the chance to look at your changes and understand what you mean by "I started down one road and changed it up along the way".  I think that was a good idea and I will go ahead and make that change later. For now, I'll merge your code.  Thanks.

**Pull request merged**
